=== Manmadeeers/CML/lab12/note.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="info">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="trow" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="tname" />
                        <xs:element name="tprice"/>
                        <xs:element name="tamm"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
    
</xs:schema>

=== Manmadeeers/CML/lab12/site3.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet href="style.css" type="text/css"?>
<info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="note.xsd">
    <trow>
        <tname>Наименование товара</tname>
        <tprice>Цена $</tprice>
        <tamm>Кол-во единиц в наличии</tamm>
    </trow>
    <trow>
        <tname>Зачёт по КЯР</tname>
        <tprice>Бесценно</tprice>
        <tamm>150</tamm>
    </trow>
    <trow>
        <tname>Автомат(у Белодеда)</tname>
        <tprice>400 баллов рейтинга</tprice>
        <tamm>30</tamm>
    </trow>
    <trow>
        <tname>Автомат(в руках)</tname>
        <tprice>Несданная сессия</tprice>
        <tamm>150</tamm>
    </trow>
    <trow>
        <tname>Проект по ОПИ</tname>
        <tprice>2 бессонные ночи</tprice>
        <tamm>1</tamm>
    </trow>
    <trow>
        <tname>Понимание АЛОВС</tname>
        <tprice>Жизнь</tprice>
        <tamm>0</tamm>
    </trow>
    
</info>
